apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nextcloud 
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: nextcloud 
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
    app.openshift.io/runtime: python
  name: nextcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        imagePullPolicy: Always
        image: quay.io/reavessm/nextcloud:latest
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          value: "nextcloud"
        - name: MYSQL_PASSWORD
          value: "nextcloud"
        - name: NEXTCLOUD_ADMIN_USER
          value: "nextcloud"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: "nextcloud"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nextcloud-asifm-test.apps.lon2-1.hyve.cloud"
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
      - name: nginx
        image: quay.io/cloud-bulldozer/nginx:latest
        ports: 
        - containerPort: 8080
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        - name: nginx-conf
          mountPath: /etc/nginx

      volumes: 
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-pvc

      - name: nginx-conf
        configMap:
          name: nginx-config
