apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nextcloud 
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: nextcloud 
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
    app.openshift.io/runtime: python
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        imagePullPolicy: Always
        image: quay.io/linuxserver.io/nextcloud:latest
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: nextcloud-data
          mountPath: /data
        - name: nextcloud-config
          mountPath: /config
        env:
        # - name: MYSQL_HOST
        #   value: mysql
        # - name: MYSQL_DATABASE
        #   value: "nextcloud"
        # - name: MYSQL_USER
        #   value: "nextcloud"
        # - name: MYSQL_PASSWORD
        #   value: "nextcloud"
        # - name: NEXTCLOUD_ADMIN_USER
        #   value: "nextcloud"
        # - name: NEXTCLOUD_ADMIN_PASSWORD
        #   value: "nextcloud"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
      volumes: 
      - name: nextcloud-data
        emptyDir: {}
      - name: nextcloud-config
        emptyDir: {}
