apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nextcloud
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud 
    app.openshift.io/runtime: php
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      containers:
      - name: nextcloud
        imagePullPolicy: Always
        image: quay.io/prometheus/prometheus:latest
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
      volumes: 
        - name: prometheus-data
          emptyDir: {}
